services:
  postgres-db:
    container_name: postgres-db
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${DB_NAME}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - e-commerce-network

  liquibase:
    image: liquibase/liquibase:4.33
    container_name: liquibase
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./packages/e-commerce-db/changelog:/liquibase/changelog
    command:
      - --url=jdbc:postgresql://postgres-db:${DB_PORT}/${DB_NAME}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - --changeLogFile=db.changelog-master.yaml
      - --searchPath=/liquibase/changelog
      - update
      - -DadminPassword=${ADMIN_PASSWORD:?ADMIN_PASSWORD is required. Run ansible/setup.sh or add ADMIN_PASSWORD to .env}
    networks:
      - e-commerce-network

  seft-runner:
    container_name: seft-runner
    build:
      context: docker/seft-hosted-runner
      dockerfile: dockerfile
      args:
        - RUNNER_TOKEN=${RUNNER_TOKEN}
        - RUNNER_NAME=${RUNNER_NAME}
    environment:
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres-db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres-db
    networks:
      - e-commerce-network

networks:
  e-commerce-network:
    driver: bridge
volumes:
  pg_data:

    # docker compose down containername -v -- down and remove volumes
    # docker compose up -d -- build -- build and run in detached mode
    # docker compose logs -f -- follow logs
    # docker compose exec postgres-db bash -- enter the postgres-db container
