---
- name: Cập nhật cache gói
  apt:
    update_cache: yes
    upgrade: yes
  become: true
- name: Cài đặt các gói
  apt:
    name:
      - git
      - gh
      - fzf
      - jq
      - anacron
      - openjdk-21-jdk
      - unzip
    state: latest
    update_cache: yes
  become: true
# Các gói liên quan đến WSL và GUI chỉ cần thiết trong môi trường phát triển local
- name: Cài đặt các gói (chỉ dành cho local)
  apt:
    name:
      - wslu
      - libgraphene-1.0-0
      - gnupg
    state: latest
  become: true
  when: is_local | default(true)
