name: "[CI] OpenAPI Typespec Build and Test"

on:
  pull_request:
    types: [assigned]
    paths:
      - "packages/openapi-typespec/**"
      - ".github/workflows/ci-openapi-typespec.yml"
      - "!packages/openapi-typespec/.vscode/**"
      - "!packages/openapi-typespec/*.code-workspace"

jobs:
  resolve-runner:
    runs-on: ubuntu-24.04
    outputs:
      runner: ${{ steps.set.outputs.runner }}
    steps:
      - name: Set runner
        id: set
        run: |
          if echo '${{ toJSON(github.event.pull_request.labels.*.name) }}' | grep -q 'self-hosted'; then
            echo 'runner=["self-hosted", "${{ github.event.sender.login }}"]' >> $GITHUB_OUTPUT
          else
            echo 'runner=["ubuntu-24.04"]' >> $GITHUB_OUTPUT
          fi

  ci-check:
    needs: resolve-runner
    runs-on: ${{ fromJSON(needs.resolve-runner.outputs.runner) }}
    env:
      NODE_VERSION: "22.17.0"
      PNPM_VERSION: "10"
    defaults:
      run:
        working-directory: ./packages/openapi-typespec
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: ${{env.PNPM_VERSION}}

      - name: Install Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v6
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: "pnpm"
          cache-dependency-path: packages/openapi-typespec/pnpm-lock.yaml

      - name: Install Typespec Compiler
        run: pnpm add -g @typespec/compiler

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate OpenAPI files
        run: pnpm run generate
